Python For DS
PRACTICAL NO 4

Name : Amit Umarvaish      Subject : PDS 
Roll no : 44               Batch : 1st
Class : SY IT              Date of submission : 05/08/26

a. Write a python code to create Numpy Array.

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])

print(a)
print("Amit 44")


[1 2 3 4 5]
Amit 44


b. Write a python code to demonstrate basic operations on single array.

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])

print(a+2)
print("Amit 44")

[3 4 5 6 7]
Amit 44


c. Write a python code to create array with 10 elements and slice element
from 1st to 5th element.

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])

print(a[1:5])
print(a[5:9])
print("Amit 44")

[2 3 4 5]
[6 7 8 9]
Amit 44


d. Write a python code to sort an array alphabetically.

In [ ]:
import numpy as np
name = np.array(["Akuv", "Amit", "Raj", "Jay"])
print (np.sort(name))

print("Amit 44")

['Akuv' 'Amit' 'Jay' 'Raj']
Amit 44


e. Write a python code to create a filter array that will return maximum
values from an array.

In [ ]:
import numpy as np
b = np.array([100,200,300,400,500])
print(b[b > 300])

print("Amit 44")

[400 500]
Amit 44
